import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/HeaderWOLogin";
import LoginHeader from "./components/HeaderLogin"
import Footer from "./components/Footer";
import styles from "./page.module.css";
import TokenProvider, { TokenContext } from "./context/TokenContext";
import { useContext } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const {isLoggedIn} = useContext(TokenContext);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${styles.body}`}>
        <TokenProvider>
          { (isLoggedIn == true) ? <Header></Header> : <LoginHeader></LoginHeader>}
          <main className={styles.main}>
            {children}
            <Footer></Footer>
          </main>
        </TokenProvider>
      </body>
    </html>
  );
}
